# -*- coding: utf-8 -*-
"""Correlation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dTWi3bk20vFxdPiPqUDFqpfgC2iH8e18
"""

print("correlation")

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Sample DataFrame
data = {
    'Age': [23, 25, 47, 35, 19, 29, 42, 55],
    'Salary': [25000, 27000, 60000, 45000, 20000, 32000, 58000, 72000],
    'Experience': [1, 2, 15, 10, 0, 3, 12, 20]
}

df = pd.DataFrame(data)

# Compute Correlation Matrix
correlation_matrix = df.corr()

# Print Correlation Matrix
print("Correlation Matrix:")
print(correlation_matrix)

# Visualize using a Heatmap
plt.figure(figsize=(6, 4))
sns.heatmap(correlation_matrix, annot=True, cmap="coolwarm", fmt=".2f")
plt.title("Correlation Matrix Heatmap")
plt.show()