# -*- coding: utf-8 -*-
"""Multi linear regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dTWi3bk20vFxdPiPqUDFqpfgC2iH8e18
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from statsmodels.graphics.regressionplots import influence_plot
import statsmodels.formula.api as smf

import pandas as pd
from google.colab import files
uploaded = files.upload()

file_name = list(uploaded.keys())[0]
cars = pd.read_csv(file_name)

cars.shape

cars.describe

cars.info

cars.head()

cars.isna().sum()

