# -*- coding: utf-8 -*-
"""News_paper.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Kmfz4xpj1aHA_q0bOTL-5OzgeUyXBOSW
"""



import pandas as pd
from google.colab import files

uploaded = files.upload()

for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn, length=len(uploaded[fn])))

df = pd.read_csv(list(uploaded.keys())[0])
df

df_new = df[['daily','sunday']]
df_new.info()

df_new.corr()

import seaborn as sns
sns.distplot(df['daily'])

import seaborn as sns
sns.distplot(df['sunday'])

import statsmodels.formula.api as smf
lm = smf.ols(formula='daily ~ sunday', data=df).fit()

sns.regplot(x="daily",y="sunday",data=df);

